version: '3.8'
services:
  flask:
    build:
      context: .
      dockerfile: elib.Dockerfile
    container_name: flask-elib
    ports:
      - "8080:8080"
    depends_on:
      - mongo
    networks:
      - flask-mongo-network

  mongo:
    image: mongo:7.0.2
    container_name: mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_LOGIN}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD}
    volumes:
      - ./database_data:/data/db
    networks:
      - flask-mongo-network

  mongo-express:
    image: mongo-express
    container_name: mongo-express
    restart: always
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_ROOT_LOGIN}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_ROOT_PASSWORD}
      ME_CONFIG_BASICAUTH_USERNAME: ${MONGO_EXPRESS_ADMIN_LOGIN}
      ME_CONFIG_BASICAUTH_PASSWORD: ${MONGO_EXPRESS_ADMIN_PASSWORD}
      ME_CONFIG_MONGODB_SERVER: mongodb
    networks:
      - flask-mongo-network

networks:
  flask-mongo-network:
    driver: bridge